/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.batteryworkshop.view.modal;

import com.batteryworkshop.model.dao.DetallePermisoDao;
import com.batteryworkshop.model.DetallePermiso;
import com.batteryworkshop.model.Permiso;
import javax.swing.JOptionPane;

/**
 *
 * @author JuniorMiguel
 */
public class FrmGestionarPermiso extends javax.swing.JInternalFrame {

    DetallePermisoDao detalleC = new DetallePermisoDao();
    public static int idRol;

    /**
     * Creates new form FrmGestionarPermiso
     */
    public FrmGestionarPermiso() {
        initComponents();
        cargarPermisos();
    }

    public void cargarPermisos() {
        DetallePermiso detalle = detalleC.listar(idRol);
        //el permiso 1 viaja aca y lo cargamos en permiso
        for (Permiso permiso : detalle.getPermiso()) {
            switch (permiso.getPermisoId()) {
                case 1:
                    chkMantenimiento.setSelected(true);
                    break;
                case 2:
                    chkVenta.setSelected(true);
                    break;
                case 3:
                    chkPedido.setSelected(true);
                    break;
                case 4:
                    chkClientes.setSelected(true);
                    break;
                case 5:
                    chkProveedores.setSelected(true);
                    break;
                case 6:
                    chkReportes.setSelected(true);
                    break;
                case 7:
                    chkAdmin.setSelected(true);
                    break;
            }
        }

    }

    private void grabar() {

        detalleC.eliminarPermisos(idRol);
        if (chkMantenimiento.isSelected()) {
            detalleC.registrarPermiso(idRol, Integer.parseInt(chkMantenimiento.getName()));
        }
        if (chkVenta.isSelected()) {
            detalleC.registrarPermiso(idRol, Integer.parseInt(chkVenta.getName()));
        }
        if (chkPedido.isSelected()) {
            detalleC.registrarPermiso(idRol, Integer.parseInt(chkPedido.getName()));
        }
        if (chkClientes.isSelected()) {
            detalleC.registrarPermiso(idRol, Integer.parseInt(chkClientes.getName()));
        }
        if (chkProveedores.isSelected()) {
            detalleC.registrarPermiso(idRol, Integer.parseInt(chkProveedores.getName()));
        }
        if (chkReportes.isSelected()) {
            detalleC.registrarPermiso(idRol, Integer.parseInt(chkReportes.getName()));
        }
        if (chkAdmin.isSelected()) {
            detalleC.registrarPermiso(idRol, Integer.parseInt(chkAdmin.getName()));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chkMantenimiento = new javax.swing.JCheckBox();
        chkProveedores = new javax.swing.JCheckBox();
        chkClientes = new javax.swing.JCheckBox();
        chkAdmin = new javax.swing.JCheckBox();
        chkVenta = new javax.swing.JCheckBox();
        chkPedido = new javax.swing.JCheckBox();
        chkReportes = new javax.swing.JCheckBox();
        cmdGrabar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Gestionar Permisos");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        chkMantenimiento.setText("Menu Mantenimiento");
        chkMantenimiento.setName("1"); // NOI18N

        chkProveedores.setText("Menu Proveedores");
        chkProveedores.setName("5"); // NOI18N

        chkClientes.setText("Menu Clientes");
        chkClientes.setName("4"); // NOI18N

        chkAdmin.setText("Menu Admin");
        chkAdmin.setName("7"); // NOI18N

        chkVenta.setText("Menu Venta");
        chkVenta.setName("2"); // NOI18N

        chkPedido.setText("Menu Pedido");
        chkPedido.setName("3"); // NOI18N

        chkReportes.setText("Menu Reportes");
        chkReportes.setName("6"); // NOI18N

        cmdGrabar.setBackground(new java.awt.Color(27, 118, 253));
        cmdGrabar.setText("Grabar");
        cmdGrabar.setName("cmdGrabar"); // NOI18N
        cmdGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGrabarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkProveedores)
                    .addComponent(chkAdmin)
                    .addComponent(chkClientes)
                    .addComponent(chkMantenimiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chkVenta)
                            .addComponent(chkPedido))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkReportes)
                        .addGap(0, 29, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMantenimiento)
                    .addComponent(chkVenta))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkProveedores)
                    .addComponent(chkPedido))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkClientes)
                    .addComponent(chkReportes))
                .addGap(33, 33, 33)
                .addComponent(chkAdmin)
                .addGap(18, 18, 18)
                .addComponent(cmdGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGrabarActionPerformed
        grabar();
        JOptionPane.showMessageDialog(null, "Los Permisos Se Grabaron Correctamente");
        dispose();
    }//GEN-LAST:event_cmdGrabarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkAdmin;
    private javax.swing.JCheckBox chkClientes;
    private javax.swing.JCheckBox chkMantenimiento;
    private javax.swing.JCheckBox chkPedido;
    private javax.swing.JCheckBox chkProveedores;
    private javax.swing.JCheckBox chkReportes;
    private javax.swing.JCheckBox chkVenta;
    public static javax.swing.JButton cmdGrabar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
