/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.batteryworkshop.view.modal;

import com.batteryworkshop.model.dao.RolDao;
import com.batteryworkshop.model.Rol;
import com.batteryworkshop.view.FrmGestionarRol;
import javax.swing.JOptionPane;

/**
 *
 * @author JuniorMiguel
 */
public final class FrmRegistrarRol extends javax.swing.JInternalFrame {

    RolDao rolC = new RolDao();
    public static int idRol = 0; // se utiliza para poder modificar y de tipo estatico para que los valors no cambien
    //cierre o no cierre el valor nunca va a cambiar
    public static boolean vista = false;

    /**
     * Creates new form FrmRegistrarRol
     */
    public FrmRegistrarRol() {
        initComponents();
        acciones();
    }

    void acciones() {

        if (vista) {

            txtDescripcion.setEnabled(false);
            cmdGrabar.setEnabled(false);

        }
        if (idRol > 0) {

            Rol rolV = (Rol) rolC.obtenerObjecto(idRol);
            txtDescripcion.setText(rolV.getDescripcion());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        cmdGrabar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Registrar Rol");
        setToolTipText("");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Descripcion");

        txtDescripcion.setFont(new java.awt.Font("Segoe UI Symbol", 0, 15)); // NOI18N

        cmdGrabar.setBackground(new java.awt.Color(27, 118, 253));
        cmdGrabar.setText("Grabar");
        cmdGrabar.setName("cmdGrabar"); // NOI18N
        cmdGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGrabarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmdGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(cmdGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGrabarActionPerformed
        grabar();
    }//GEN-LAST:event_cmdGrabarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        idRol=0;
        vista=false;
       
    }//GEN-LAST:event_formInternalFrameClosed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        idRol=0;
        vista=false;
        
    }//GEN-LAST:event_formInternalFrameClosing
    void grabar() {
        if (txtDescripcion.getText().isEmpty()) {
//            Alerta alerta = new Alerta("ALERTA", "La desccripción es obligatoria");
            JOptionPane.showMessageDialog(null, "La desccripción es obligatoria");
            return;
        }
        Rol rol = new Rol();
        rol.setDescripcion(txtDescripcion.getText().toUpperCase());

        if (cmdGrabar.getText().equalsIgnoreCase("Grabar")) {
            try {
                rolC.registrar(rol);
                JOptionPane.showMessageDialog(null, "Rol Se Registro Correctamente");
//                AlertaBien alerta = new AlertaBien("MENSAJE", "El rol se registro correctamente");
                this.dispose();
                FrmGestionarRol.listar("");

            } catch (Exception e) {
//                AlertaError error = new AlertaError("ERROR", e.getMessage());
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } else {
            try {
                rol.setRolId(idRol);
                rolC.editar(rol);
//                AlertaBien alerta = new AlertaBien("MENSAJE", "El rol se actulizó correctamente");
                JOptionPane.showMessageDialog(null, "Los Datos Se Actualizarón Correctamente");
                this.dispose();
                FrmGestionarRol.listar("");

            } catch (Exception e) {
//                AlertaError error = new AlertaError("ERROR", e.getMessage());
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }   

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton cmdGrabar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
